services:
  keystore-backend:
    image: keystore-backend
    container_name: keystore-backend
    build:
      context: .
      dockerfile: KeyStore/Dockerfile
    ports:
      - "16874:8080"
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: pg
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
