name: Build and Test KeyStore

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore KeyStore.sln

      - name: Build solution
        run: dotnet build KeyStore.sln --configuration Release --no-restore

      - name: Publish test project
        run: dotnet publish KeyStore.Tests/KeyStore.Tests.csproj --configuration Release --output ./published-tests

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: ./published-tests

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: test-artifacts
          path: ./tests

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Run tests
        run: dotnet test ./tests/KeyStore.Tests.dll --logger trx
